from lc import *

# https://leetcode.com/problems/lexicographically-smallest-generated-string/?envType=daily-question&envId=2026-03-31

class Solution:
    def generateString(self, str1: str, str2: str) -> str:
        n, m = len(str1), len(str2)
        s = ["a"] * (n + m - 1)
        fixed = [False] * (n + m - 1)
        for i, ch in enumerate(str1):
            if ch == "T":
                for j, c in enumerate(str2, i):
                    if fixed[j] and s[j] != c:
                        return ""
                    s[j], fixed[j] = c, True
        for i, ch in enumerate(str1):
            if ch == "F":
                if any(str2[j - i] != s[j] for j in range(i, i + m)):
                    continue
                for j in range(i + m - 1, i - 1, -1):
                    if not fixed[j]:
                        s[j] = "b"
                        break
                else:
                    return ""
        return "".join(s)

class Solution:
    def generateString(self, a: str, b: str) -> str:
        n,m=len(a),len(b);t,f,s=['a']*(n+m-1),[0]*(n+m-1),setitem
        if any(x=='T'and any(y!=t[i+j]!=y and f[i+j]or s(t,i+j,y)or s(f,i+j,1)for j,y in enumerate(b))for i, x in enumerate(a)):
            return ''
        if any(x=='F'and[*b]==t[i:i+m]and not any(not f[j]and not s(t,j,'b')for j in range(i+m-1,i-1,-1))for i, x in enumerate(a)):
            return ''
        return ''.join(t)

class Solution:
    def generateString(self, a: str, b: str) -> str:
        m=len(b);k=len(a)+m-1;t,f=['a']*k,[0]*k;s,e=setitem,enumerate;return''if any(x=='T'and any(y!=t[i+j]and f[i+j]or s(t,i+j,y)or s(f,i+j,1)for j,y in e(b))for i,x in e(a))or any(x=='F'and[*b]==t[i:i+m]and all(f[j]or s(t,j,'b')for j in range(i+m-1,i-1,-1))for i,x in e(a))else''.join(t)

test('''
3474. Lexicographically Smallest Generated String
Solved
Hard
Topics
premium lock icon
Companies
Hint
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".

 

Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index   T/F Substring of length m
0   'T' "ab"
1   'F' "ba"
2   'T' "ab"
3   'F' "ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"

 

Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.
 
Seen this question in a real interview before?
1/5
Yes
No
Accepted
5,697/17.9K
Acceptance Rate
31.9%
Topics
Principal
String
Greedy
String Matching
Weekly Contest 439
icon
Companies
Hint 1
Use dynamic programming.
Hint 2
Fill the fixed part.
Hint 3
Use KMP's next table for DP.
Hint 4
The state is the prefix length and the longest suffix length that matches the pattern.
Hint 5
Each unknown character can be selected from ['a', 'b'].
Hint 6
Can you think of a greedy approach?
Similar Questions
Lexicographically Smallest Equivalent String
Medium
''')
