from lc import *

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        r = 0
        for c in s+t:
            r ^= ord(c)
        return chr(r)

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        return chr(reduce(lambda x,y:x^y,map(ord,s+t)))

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        return next(iter(Counter(t)-Counter(s)))

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        return ''.join(Counter(t)-Counter(s))

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        c=Counter;return''.join(c(t)-c(s))

test('''
389. Find the Difference
Easy

4220

441

Add to List

Share
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
Accepted
545,930
Submissions
923,252
''')

